"""make_jsonb_fields_not_null

Revision ID: 86fabbe0aad3
Revises: 9a836d44e1ac
Create Date: 2025-08-19 18:13:10.008059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86fabbe0aad3'
down_revision: Union[str, Sequence[str], None] = '9a836d44e1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'draft_order_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_sessions', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_user_sessions_phone_number'), table_name='user_sessions')
    op.create_unique_constraint(None, 'user_sessions', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_phone_number'), 'user_sessions', ['phone_number'], unique=True)
    op.alter_column('user_sessions', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_sessions', 'draft_order_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
