"""improve_user_sessions_jsonb_and_constraints

Revision ID: 9a836d44e1ac
Revises: ac5bdf84f388
Create Date: 2025-08-19 18:02:28.820998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a836d44e1ac'
down_revision: Union[str, Sequence[str], None] = 'ac5bdf84f388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Manual conversion from TEXT to JSONB using USING clause
    op.execute("ALTER TABLE user_sessions ALTER COLUMN draft_order_json TYPE JSONB USING COALESCE(draft_order_json::jsonb, '{}'::jsonb)")
    op.execute("ALTER TABLE user_sessions ALTER COLUMN context_data TYPE JSONB USING COALESCE(context_data::jsonb, '{}'::jsonb)")
    
    # Set default values for existing NULL records
    op.execute("UPDATE user_sessions SET draft_order_json = '{}' WHERE draft_order_json IS NULL")
    op.execute("UPDATE user_sessions SET context_data = '{}' WHERE context_data IS NULL")
    
    op.drop_constraint(op.f('user_sessions_cliente_id_key'), 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_phone_number'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_phone_number'), 'user_sessions', ['phone_number'], unique=True)
    op.create_index('ix_user_sessions_last_interaction', 'user_sessions', ['last_interaction_at'], unique=False)
    
    # Add constraints
    op.create_check_constraint('ck_valid_phone_format', 'user_sessions', "phone_number ~ '^\\+[1-9][0-9]{6,15}$'")
    op.create_check_constraint('ck_valid_phase', 'user_sessions', "phase IN ('greeting', 'browsing', 'ordering', 'confirming', 'delivery', 'payment', 'completed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_valid_phase', 'user_sessions', type_='check')
    op.drop_constraint('ck_valid_phone_format', 'user_sessions', type_='check')
    op.drop_index('ix_user_sessions_last_interaction', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_phone_number'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_phone_number'), 'user_sessions', ['phone_number'], unique=False)
    op.create_unique_constraint(op.f('user_sessions_cliente_id_key'), 'user_sessions', ['cliente_id'], postgresql_nulls_not_distinct=False)
    
    # Convert back from JSONB to TEXT
    op.execute("ALTER TABLE user_sessions ALTER COLUMN context_data TYPE TEXT USING context_data::text")
    op.execute("ALTER TABLE user_sessions ALTER COLUMN draft_order_json TYPE TEXT USING draft_order_json::text")
    
    op.alter_column('user_sessions', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
